site_name: "Maré de Manguinhos"
site_description: "Documentação do Sistema da Associação Maré de Manguinhos"
site_url: "https://mare-de-manguinhos.github.io/mare-manguinhos-associacao/"
repo_url: "https://github.com/mare-de-manguinhos/mare-manguinhos-associacao"

docs_dir: docs

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    primary: teal
    accent: deep orange

nav:
  - Home: index.md
  - Guia:
    - Como Usar: COMO_USAR.md
    - Constituições & Boas Práticas: CONSTITUTIONS.md
  - Produto:
    - Épicos & Histórias: EPICS.md
  - Técnico:
    - Arquitetura: ARQUITETURA.md
    - Documentação da API: API.md

plugins:
  - search
  - section-index

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mare-de-manguinhos/mare-manguinhos-associacao
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - tables
  - toc:
      permalink: true
